POST http://localhost:8000/api/v1/writer
Content-Type: application/json

{
    "name" : "ㄴ",
    "password" : "qaz1127!"
}


###
GET http://localhost:8000/api/v1/writer/54710fe40ace468bbeb7b1be9e3b7e04


###

POST http://localhost:8000/api/v1/login
Content-Type: application/json

{    "email" : "swenginejsk@gmail.com",
    "password" : "qaz1127!"

}


###
POST http://localhost:8000/api/v1/diary
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI5MjcxNjIwLCJqdGkiOiJhMGViNjhmMjcxZmU0YmU0ODMzZWM1MGZhYTNlMTBhMiIsInVzZXJfaWQiOiJhNmM2YmM4YjFjMDU0ZjI2ODFlNTkwM2RkNDU5NGI3NCIsIm5hbWUiOiJqc2sifQ.iwyiAqmZciQ1V_5Lyt_E04bo4tbN3LN247VG6phImq8
Content-Type: application/json

{
"writer": "a6c6bc8b1c054f2681e5903dd4594b74",
"title": "test",
"contents": "test"

}

###
GET http://localhost:8000/api/v1/diary?id=a6c6bc8b1c054f2681e5903dd4594b74
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI5Mjg5ODY1LCJqdGkiOiI2ZTkyMmY0MzAzZDU0NDY2OTNmYTM3N2UzODZlMDY0YSIsInVzZXJfaWQiOiJhNmM2YmM4YjFjMDU0ZjI2ODFlNTkwM2RkNDU5NGI3NCIsIm5hbWUiOiJqc2sifQ.aZOUyXTWdTeisu_7KXpI4sv0yt-0yuaLpy2H5r_IXOM
