# Generated by Django 3.2.4 on 2021-08-03 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20210803_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 6, 15, 23, 176079, tzinfo=utc), verbose_name='생성날짜'),
        ),
    ]
