# Generated by Django 3.2.4 on 2021-08-03 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='생성날짜'),
        ),
    ]
