# Generated by Django 3.2.4 on 2021-08-03 05:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import utils.custom_field


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 5, 21, 29, 904510, tzinfo=utc), verbose_name='생성날짜'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.CharField(default=utils.custom_field.hex_uuid, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
