# Generated by Django 3.2.4 on 2021-08-18 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diary_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='업데이트날짜'),
        ),
    ]
