# Generated by Django 3.2.4 on 2021-08-10 05:47

from django.db import migrations
import utils.custom_field
import writer.validators


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0006_alter_writer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='email',
            field=utils.custom_field.CaseLowerEmailField(help_text='writer login ID', max_length=64, unique=True, validators=[writer.validators.validate_email], verbose_name='이메일'),
        ),
    ]
