# Generated by Django 3.2.4 on 2021-08-03 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='email',
            field=models.EmailField(help_text='writer login ID', max_length=64, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='관리자페이지접속여부'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='관리자여부'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='name',
            field=models.CharField(help_text='user name (firstname + second_name)', max_length=30, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='업데이트일'),
        ),
    ]
